export const PROFILES = [
  {
    id: '1',
    name: 'Lara',
    age: 21,
    course: 'Medicina',
    university: 'UFBA',
    bio: 'Vivendo à base de café e xerox. Procuro alguém pra dividir o fardo dos estudos e as alegrias do fim de semana.',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    name: 'Pedro',
    age: 23,
    course: 'Eng. de Computação',
    university: 'UNIFACS',
    bio: 'Entre códigos e projetos, busco um bug no meu coração. Me chama pra um açaí pós-aula.',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: '3',
    name: 'Mariana',
    age: 22,
    course: 'Direito',
    university: 'UFBA',
    bio: 'Futura advogada, mas no momento só sei acusar o sono que eu perco estudando. Vamos tomar uma e esquecer os Vade Mecuns?',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: '4',
    name: 'Lucas',
    age: 24,
    course: 'Arquitetura',
    university: 'UFBA',
    bio: 'Projetando meu futuro, mas queria incluir alguém nos planos. Adoro fotografia e explorar a cidade.',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    id: '5',
    name: 'Sofia',
    age: 20,
    course: 'Letras',
    university: 'UNEB',
    bio: 'Amante de literatura e de conversas que fluem. Me conte seu livro favorito e te pago um café.',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: '6',
    name: 'Gabriel',
    age: 25,
    course: 'Ed. Física',
    university: 'UNEB',
    bio: 'Não sou personal, mas posso te ajudar a encontrar o caminho pro meu coração. Gosto de praia e esportes.',
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
    {
    id: '7',
    name: 'Julia',
    age: 22,
    course: 'Psicologia',
    university: 'UFBA',
    bio: 'Analisando tudo, menos a minha vida amorosa. Que tal uma sessão de terapia mútua no bar?',
    image: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    id: '8',
    name: 'Mateus',
    age: 26,
    course: 'Odontologia',
    university: 'UFBA',
    bio: 'Prometo não julgar seu sorriso. Buscando alguém pra compartilhar a playlist e as contas do bar.',
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
];

